// Code generated by protoc-gen-go. DO NOT EDIT.
// source: combytes.proto

package COMbytes

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Bytes struct {
	T                    []string `protobuf:"bytes,1,rep,name=T" json:"T,omitempty"`
	R                    []string `protobuf:"bytes,2,rep,name=R" json:"R,omitempty"`
	S                    []string `protobuf:"bytes,3,rep,name=S" json:"S,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bytes) Reset()         { *m = Bytes{} }
func (m *Bytes) String() string { return proto.CompactTextString(m) }
func (*Bytes) ProtoMessage()    {}
func (*Bytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_36b7c93fff0c8065, []int{0}
}

func (m *Bytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bytes.Unmarshal(m, b)
}
func (m *Bytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bytes.Marshal(b, m, deterministic)
}
func (m *Bytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bytes.Merge(m, src)
}
func (m *Bytes) XXX_Size() int {
	return xxx_messageInfo_Bytes.Size(m)
}
func (m *Bytes) XXX_DiscardUnknown() {
	xxx_messageInfo_Bytes.DiscardUnknown(m)
}

var xxx_messageInfo_Bytes proto.InternalMessageInfo

func (m *Bytes) GetT() []string {
	if m != nil {
		return m.T
	}
	return nil
}

func (m *Bytes) GetR() []string {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *Bytes) GetS() []string {
	if m != nil {
		return m.S
	}
	return nil
}

func init() {
	proto.RegisterType((*Bytes)(nil), "COMbytes.Bytes")
}

func init() { proto.RegisterFile("combytes.proto", fileDescriptor_36b7c93fff0c8065) }

var fileDescriptor_36b7c93fff0c8065 = []byte{
	// 76 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0xcf, 0x4d,
	0xaa, 0x2c, 0x49, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x70, 0xf6, 0xf7, 0x05,
	0xf3, 0x95, 0x34, 0xb8, 0x58, 0x9d, 0x40, 0x0c, 0x21, 0x4e, 0x2e, 0xc6, 0x10, 0x09, 0x46, 0x05,
	0x66, 0x0d, 0x4e, 0x10, 0x33, 0x48, 0x82, 0x09, 0xc6, 0x0c, 0x96, 0x60, 0x06, 0x31, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xa8, 0x27, 0xd3, 0x85, 0x44, 0x00, 0x00, 0x00,
}
