// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dpres.proto

package DPres

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	R                    [][]byte `protobuf:"bytes,1,rep,name=R,json=r" json:"R,omitempty"`
	C                    [][]byte `protobuf:"bytes,2,rep,name=C,json=c" json:"C,omitempty"`
	Proof                [][]byte `protobuf:"bytes,3,rep,name=Proof,json=proof" json:"Proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_25c9a1714ea5bffd, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetR() [][]byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *Response) GetC() [][]byte {
	if m != nil {
		return m.C
	}
	return nil
}

func (m *Response) GetProof() [][]byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "DPres.Response")
}

func init() { proto.RegisterFile("dpres.proto", fileDescriptor_25c9a1714ea5bffd) }

var fileDescriptor_25c9a1714ea5bffd = []byte{
	// 94 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x29, 0x28, 0x4a,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x75, 0x09, 0x28, 0x4a, 0x2d, 0x56, 0xb2,
	0xe1, 0xe2, 0x08, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0xe2, 0xe1, 0x62, 0x0c, 0x92,
	0x60, 0x54, 0x60, 0xd6, 0xe0, 0x09, 0x62, 0x2c, 0x02, 0xf1, 0x9c, 0x25, 0x98, 0x20, 0xbc, 0x64,
	0x21, 0x11, 0x2e, 0xd6, 0x80, 0xa2, 0xfc, 0xfc, 0x34, 0x09, 0x66, 0xb0, 0x08, 0x6b, 0x01, 0x88,
	0x03, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xea, 0x66, 0x52, 0x52, 0x00, 0x00, 0x00,
}
