// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comtime.proto

package COMtime

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Time struct {
	T                    []string `protobuf:"bytes,1,rep,name=T" json:"T,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea9d7793c5ab6fca, []int{0}
}

func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetT() []string {
	if m != nil {
		return m.T
	}
	return nil
}

func init() {
	proto.RegisterType((*Time)(nil), "COMtime.Time")
}

func init() { proto.RegisterFile("comtime.proto", fileDescriptor_ea9d7793c5ab6fca) }

var fileDescriptor_ea9d7793c5ab6fca = []byte{
	// 65 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0x2d,
	0xc9, 0xcc, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x77, 0xf6, 0xf7, 0x05, 0x71,
	0x95, 0x04, 0xb9, 0x58, 0x42, 0x32, 0x73, 0x53, 0x85, 0x38, 0xb9, 0x18, 0x43, 0x24, 0x18, 0x15,
	0x98, 0x35, 0x38, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x87, 0xd2, 0x5a, 0xf9, 0x2b, 0x00, 0x00,
	0x00,
}
